### PR TITLE
Calendar map location

### LINKED ISSUE #104: [BUG] Different Calendars are not properly listed
**Describe the bug**
When the user signs into their google calendar account, the 1st calendar which is active by default is Schedule 2. Also, the list of schedules should be in proper order

**To Reproduce**
1. Go to Calendar
2. Sign in
3. The default item will show schedule 2
4. When clicking on it the 1st element of the list is schedule 2.

**Expected behavior**
Schedule 1 should be the default and 1st in the list.

**Screenshots**
View the provided screenshot of the bug.

**Additional context**
No additional context required.

### PR DESCRIPTION
**Pull request by anhtuann**
- Fixed directions not showing a route on the map 

- Fixed bug where schedule 2 displays as the default schedule when opening calendar tab
- Fixed calendar selection menu where schedule 1 was not the first schedule

closes #104 #52

### CODE REVIEW

File: Concordia_Campus_App/maps/MapScreen.js [hunk 1]
```diff
@@ -264,6 +266,51 @@ const handleUserLocation = () => {
...
 
+  useEffect(() => {
+    if (destinationLoc) {
+      console.log('Destination Location:', destinationLoc);
+      
+      const selectedBuilding = buildingsData.buildings.find(
+        (building) => building.name === destinationLoc
+      );
+  
+      if (selectedBuilding) {
```
Comment (Otterboi) [inline Concordia_Campus_App/maps/MapScreen.js:277]: should show a different color when the building is selected, i believe this code should do that but i do not see any color changes when pressing the location button

**Review by Otterboi — CHANGES_REQUESTED** [review]
The code looks good, but when the user gets directions or finds the location, the building color should be different to indicate that's where they need to go.

File: Concordia_Campus_App/maps/MapScreen.js (hunk 1 above)
Comment (anhtuann) [reply Concordia_Campus_App/maps/MapScreen.js:277]: absolutely, I have changed the color of the building to orange when the user presses the location and directions buttons

Comment (Otterboi) [reply Concordia_Campus_App/maps/MapScreen.js:277]: looks great

**Review by Otterboi — CHANGES_REQUESTED** [review]
This might be a bug, but the color and directions will stay on screen forever. Maybe adding a way to reset these functionalities. For example, if choosing a different campus it would reset the screen

**Review by Otterboi — APPROVED** [review]
Looks great all edits added correctly
